### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bmann** [ethresearch/en-ethereum-wiki#2]
I realize that me creating https://github.com/ethresearch/en-ethereum-wiki/blob/master/roadmap.md may be considered "controversial".

I hope it can be useful as a place to gather content and point to discussions and proposals.

_Maybe_ it can be moved to a ```roadmap``` directory with access control from the wikijs front end so changes are through PRs only.

Let me know how I can help.

**Comment by virgil** [comment]
Eh just go for it. Post/Modify anything you'd like.
